#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS auth_schema AUTHORIZATION $POSTGRES_USER;
    CREATE SCHEMA IF NOT EXISTS patient_schema AUTHORIZATION $POSTGRES_USER;
    CREATE SCHEMA IF NOT EXISTS clinical_schema AUTHORIZATION $POSTGRES_USER;
EOSQL