CREATE SCHEMA IF NOT EXISTS auth_schema;
CREATE SCHEMA IF NOT EXISTS patient_schema;
CREATE SCHEMA IF NOT EXISTS clinical_schema;
CREATE SCHEMA IF NOT EXISTS lab_schema;
CREATE SCHEMA IF NOT EXISTS pharmacy_schema;
CREATE SCHEMA IF NOT EXISTS billing_schema;
